Repository MetaCell/geppetto-scidash, pull requests merged in 2018-02, with the labels that each got.

#40 Fixes
  components/TestInstances.js
  components/common/griddle/ScidashDateRangeCell.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
  styles/scidash.less
Labels: bug, in progress

#41 Filtering Fix
  components/TestInstances.js
  components/common/griddle/ScidashModelDetailLinkColumn.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
Labels: bug, in progress

#43 Enabled sorting again
  components/TestInstances.js
Labels: in progress

#44 Final fixes with sorting and some filtering issues
  components/TestInstances.js
  components/common/griddle/ScidashFilterCell.js
  components/common/griddle/ScidashModelDetailLinkColumn.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
Labels: bug, in progress

#45 Clear functionality for timestamp filter
  components/common/griddle/ScidashDateRangeCell.js
Labels: enhancement, in progress

#46 Color mapping for score
  components/TestInstances.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
  styles/scidash.less
Labels: enhancement, in progress

#47 Color fix
  components/common/griddle/ScidashScoreDetailLinkColumn.js
Labels: bug, in progress

#48 Reset button
  components/common/griddle/ScidashDateRangeCell.js
Labels: in progress

#49 Model details
  components/ModelDetails.js
  components/TestInstances.js
  components/common/griddle/ScidashModelDetailLinkColumn.js
Labels: enhancement, in progress

#52 color mapping label
  components/TestInstances.js
  pages/home/Home.js
  styles/scidash.less
Labels: in progress

#53 Development roman
  common/Helper.js
  components/ModelDetails.js
  components/TestInstances.js
Labels: in progress

#54 Score details, Clickable URLs
  components/ModelDetails.js
  components/ScoreDetails.js
  components/common/griddle/ScidashModelDetailLinkColumn.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
Labels: in progress

#58 Fixes
  common/Helper.js
  components/ModelDetails.js
  components/ScoreDetails.js
  components/common/griddle/ScidashScoreDetailLinkColumn.js
Labels: in progress
