Repository MetaCell/geppetto-scidash, pull requests merged in 2019-05, with the labels that each got.

#284 Fix edit part2
  actions/creators/models.js
  actions/creators/tests.js
  components/info-dialog/InfoDialog.js
  components/model-form/ModelForm.js
  components/test-form/TestForm.js
  services/api/ModelEditApiService.js
  services/api/ModelsApiService.js
  services/api/TestEditApiService.js
  services/api/TestInstancesApiService.js
Labels: in progress

#286 Feature testing models
  components/score-details/ScoreDetailsContainer.js
  components/test-form/ParamsForm.js
Labels: in progress

#293 Feature lock/deprecated implementation part 1, to be finished the sch…
  components/model-edit/ModelEdit.js
  components/model-edit/ModelEditContainer.js
  components/model-form/ModelForm.js
  components/model-form/ParamsTable.js
  components/model-form/partials.js
  components/models/partial.js
  components/test-edit/TestEdit.js
  components/test-edit/TestEditContainer.js
  components/test-form/ParamsForm.js
  components/test-form/ParamsFormset.js
  components/test-form/TestForm.js
  components/tests/partial.js
Labels: enhancement, review

#303 Fix ui fixes
  components/model-form/ParamsTable.js
  components/models/Models.js
  components/models/partial.js
  components/page/Drawer/Drawer.js
  components/scheduling/DDListContainer.js
  components/tests/partial.js
Labels: bug

#308 Fix model url
  components/model-form/ModelForm.js
Labels: bug, enhancement

#310 Fix toggles style
  actions/creators/models.js
  actions/creators/tests.js
  components/model-form/ModelForm.js
  components/model-form/ParamsTable.js
  components/model-form/partials.js
  styles/scidash.less
Labels: bug
